kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: uat-rbd-kubeuat
provisioner: ceph.com/rbd
parameters:
  monitors: 10.10.10.14:6789,10.10.10.15:6789,10.10.10.16:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  pool: rbd
  userId: admin
  userSecretName: ceph-secret-admin
  userSecretNamespace: kube-system
  imageFormat: "2"
  imageFeatures: "layering"
