kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-nexta"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
