---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-rbd
spec:
  containers:
  - image: ubuntu-saic:16.04 
    name: test-container
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 3600"
    volumeMounts:
      - name: pvc
        mountPath: "/mnt/saic/rbd"
  restartPolicy: "Never"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: rbd-pvc-example 
