---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-cephfs
  namespace: dqtest
spec:
  nodeSelector:
    kubernetes.io/hostname: "10.10.10.13"
  containers:
  - image: ubuntu-saic:16.04 
    name: cephfs-container
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "sleep 3600"
    volumeMounts:
      - name: pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: cephfs-pvc-example

